production:
  clients:
    default:
      hosts:
        - 127.0.0.1:27017
      database: personalize_production
  options:
    raise_not_found_error: false
development:
  clients:
    default:
      hosts:
        - 127.0.0.1:27017
      database: personalize_development
  options:
    raise_not_found_error: false
test:
  clients:
    default:
      hosts:
        - 127.0.0.1:27017
      database: personalize_test
  options:
    raise_not_found_error: false
